version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/colby
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - colby-network

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: colby
    ports:
      - "5432:5432"
    networks:
      - colby-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - colby-network

networks:
  colby-network:
    driver: bridge